# Generated by Django 3.2.15 on 2025-06-12 00:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraLicitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Comentario/Acción')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Financiamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('clave', models.CharField(blank=True, help_text='Clave para login de operador', max_length=128, null=True, verbose_name='Clave de acceso')),
            ],
        ),
        migrations.CreateModel(
            name='TipoLicitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('operador', 'Operador')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ObservacionBitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Observación')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('bitacora', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='observacion', to='licitaciones.bitacoralicitacion')),
            ],
        ),
        migrations.CreateModel(
            name='Licitacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_pedido', models.IntegerField(verbose_name='N° de pedido')),
                ('numero_cuenta', models.CharField(max_length=30, verbose_name='N° de cuenta')),
                ('en_plan_anual', models.BooleanField(default=False, verbose_name='¿Está en el plan anual?')),
                ('iniciativa', models.CharField(blank=True, max_length=255, null=True)),
                ('monto_presupuestado', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Monto Presupuestado')),
                ('llamado_cotizacion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Llamado Cotización')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='licitaciones', to='licitaciones.categoria')),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licitaciones', to='licitaciones.departamento')),
                ('estado_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_estado', to='licitaciones.estado')),
                ('etapa_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_etapa', to='licitaciones.etapa')),
                ('financiamiento', models.ManyToManyField(blank=True, related_name='licitaciones', to='licitaciones.Financiamiento')),
                ('moneda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='licitaciones', to='licitaciones.moneda')),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos', to='licitaciones.operador')),
                ('tipo_licitacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licitaciones', to='licitaciones.tipolicitacion')),
            ],
            options={
                'db_table': 'licitacion_licitacion',
            },
        ),
        migrations.CreateModel(
            name='DocumentoLicitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='documentos_licitacion/')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('licitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='licitaciones.licitacion')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoBitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='documentos_licitacion/')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('bitacora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='licitaciones.bitacoralicitacion')),
            ],
        ),
        migrations.AddField(
            model_name='bitacoralicitacion',
            name='etapa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='licitaciones.etapa'),
        ),
        migrations.AddField(
            model_name='bitacoralicitacion',
            name='licitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitacoras', to='licitaciones.licitacion'),
        ),
        migrations.AddField(
            model_name='bitacoralicitacion',
            name='operador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='licitaciones.operador'),
        ),
        migrations.CreateModel(
            name='TipoLicitacionEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_licitacion_rel', to='licitaciones.etapa')),
                ('tipo_licitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas_rel', to='licitaciones.tipolicitacion')),
            ],
            options={
                'ordering': ['tipo_licitacion', 'orden'],
                'unique_together': {('tipo_licitacion', 'etapa')},
            },
        ),
    ]
