# Generated by Django 3.2.15 on 2025-06-20 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='licitacion',
            name='licitacion_fallida_linkeada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nuevas_licitaciones', to='licitaciones.licitacion', verbose_name='Licitación fallida linkeada'),
        ),
    ]
