# Generated by Django 3.2.15 on 2025-07-04 22:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('licitaciones', '0006_auto_20250704_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licitacion',
            name='operador',
        ),
        migrations.RemoveField(
            model_name='bitacoralicitacion',
            name='operador',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='operador',
        ),
        migrations.DeleteModel(
            name='Operador',
        ),
    ]
