# Generated by Django 3.2.25 on 2025-01-17 00:00
# Migración para remover completamente el modelo Operador y todas sus referencias

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0007_fix_migrar_datos_operador_a_user'),
    ]

    operations = [
        # No operations here as the model and fields seem to have been already removed
    ]
