# Generated by Django 3.2.15 on 2025-07-05 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0008_remover_modelo_operador')
    ]

    operations = [
    ]
