# Generated by Django 3.2.15 on 2025-07-05 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0009_merge_20250704_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licitacion',
            name='llamado_cotizacion',
            field=models.CharField(blank=True, choices=[('primer_llamado', 'Primer llamado'), ('segundo_llamado', 'Segundo llamado'), ('tercer_llamado', 'Tercer llamado'), ('cuarto_llamado', 'Cuarto llamado'), ('quinto_llamado', 'Quinto llamado')], max_length=20, null=True, verbose_name='Llamado Cotización'),
        ),
    ]
