# Generated by Django 3.2.15 on 2025-07-06 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('licitaciones', '0011_licitacion_tipo_fallida'),
    ]

    operations = [
        migrations.AddField(
            model_name='licitacion',
            name='operador_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licitaciones_operador_2', to=settings.AUTH_USER_MODEL, verbose_name='Operador 2'),
        ),
        migrations.AlterField(
            model_name='licitacion',
            name='operador_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licitaciones_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Operador 1'),
        ),
    ]
