# Generated by Django 3.2.15 on 2025-07-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0012_auto_20250706_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='licitacion',
            name='id_mercado_publico',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Mercado Público'),
        ),
    ]
