# Generated by Django 3.2.15 on 2025-07-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0013_licitacion_id_mercado_publico'),
    ]

    operations = [
        migrations.AddField(
            model_name='licitacion',
            name='pedido_devuelto',
            field=models.BooleanField(default=False, verbose_name='Pedido devuelto'),
        ),
    ]
