# Generated by Django 4.2.23 on 2025-08-04 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licitaciones", "0014_licitacion_pedido_devuelto"),
    ]

    operations = [
        migrations.AddField(
            model_name="licitacion",
            name="sigla",
            field=models.CharField(
                choices=[("le", "LE"), ("lp", "LP"), ("lr", "LR")],
                default="le",
                max_length=2,
                verbose_name="Sigla",
            ),
        ),
    ]
