# Generated by Django 4.2.23 on 2025-09-15 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("licitaciones", "0014_licitacion_pedido_devuelto"),
    ]

    operations = [
        migrations.AddField(
            model_name="licitacion",
            name="empresa_adjudicacion",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Empresa de adjudicación",
            ),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="fecha_apertura_economica_publicacionportal",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de apertura económica"
            ),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="fecha_apertura_tecnica_publicacionportal",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de apertura técnica"
            ),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="fecha_cierre_oferta_publicacionportal",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de cierre de oferta"
            ),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="fecha_cierre_ofertas_mercado_publico",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Fecha de cierre de ofertas en mercado público",
            ),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="fecha_cierre_preguntas_publicacionportal",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de cierre de preguntas"
            ),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="fecha_comision_evaluacion",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de comisión"
            ),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="fecha_decreto_adjudicacion",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="fecha_disponibilidad_presupuestaria",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Fecha que se pide disponibilidad presupuestaria",
            ),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="fecha_estimada_adjudicacion_publicacionportal",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha estimada de adjudicación"
            ),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="fecha_evaluacion_cotizacion",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Fecha de evaluacion de la cotizacion",
            ),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="fecha_evaluacion_tecnica_evaluacion",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Fecha que se envía evaluación técnica",
            ),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="fecha_publicación_mercado_publico",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Fecha de publicación en mercado público",
            ),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="fecha_recepcion_documento_regimen_interno",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de llegada de documento"
            ),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="fecha_respuesta_publicacionportal",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de respuesta"
            ),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="fecha_solicitud_intencion_compra",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Fecha de la solicitud de intencion de compra",
            ),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="fecha_solicitud_regimen_interno",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Fecha de solicitud de régimen interno",
            ),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="fecha_subida_mercado_publico_adjudicacion",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Fecha de subida de adjudicación a mercado público",
            ),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="fecha_tentativa_cierre",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha tentativa de cierre"
            ),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="fecha_tope_firma_contrato",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha tope de firma de contrato"
            ),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="fecha_visita_terreno_publicacionportal",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de visita a terreno"
            ),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="monto_adjudicacion",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                null=True,
                verbose_name="Fecha de decreto de adjudicación",
            ),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="monto_estimado_cotizacion",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                null=True,
                verbose_name="Monto estimado de cotización",
            ),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="nombre_integrante_dos_comision_base",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Integrante dos de la comisión",
            ),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="nombre_integrante_dos_evaluacion",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Integrante dos evaluación",
            ),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="nombre_integrante_tres_comision_base",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Integrante tres de la comisión",
            ),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="nombre_integrante_tres_evaluacion",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Integrante tres evaluación",
            ),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="nombre_integrante_uno_comision_base",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Integrante uno de la comisión",
            ),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="nombre_integrante_uno_evaluacion",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Integrante uno evaluación",
            ),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="orden_compra_adjudicacion",
            field=models.IntegerField(
                blank=True,
                default=0,
                null=True,
                verbose_name="Orden de compra de adjudicación",
            ),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="rut_adjudicacion",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Rut de empresa de adjudicación",
            ),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="tipo_presupuesto",
            field=models.CharField(
                choices=[("le", "LE"), ("lp", "LP"), ("lr", "LR")],
                default="le",
                max_length=2,
                null=True,
                verbose_name="Tipo por presupuesto",
            ),
        ),
        migrations.CreateModel(
            name="DocumentoObservacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archivo", models.FileField(upload_to="documentos_licitacion/")),
                ("nombre", models.CharField(blank=True, max_length=255, null=True)),
                ("fecha_subida", models.DateTimeField(auto_now_add=True)),
                (
                    "bitacora",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archivos",
                        to="licitaciones.observacionbitacora",
                    ),
                ),
            ],
        ),
    ]
