# Generated by Django 4.2.23 on 2025-08-28 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("licitaciones", "0014_licitacion_pedido_devuelto"),
    ]

    operations = [
        migrations.AddField(
            model_name="licitacion",
            name="empresa_adjudicacion",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="fecha_apertura_economica_publicacionportal",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de apertura económica"
            ),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="fecha_apertura_tecnica_publicacionportal",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de apertura técnica"
            ),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="fecha_cierre_oferta_publicacionportal",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de cierre de oferta"
            ),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="fecha_cierre_preguntas_publicacionportal",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de cierre de preguntas"
            ),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="fecha_comision_evaluacion",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de comisión"
            ),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="fecha_decreto_adjudicacion",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="fecha_disponibilidad_presupuestaria",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Fecha que se pide disponibilidad presupuestaria",
            ),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="fecha_estimada_adjudicacion_publicacionportal",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha estimada de adjudicación"
            ),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="fecha_evaluacion_tecnica_evaluacion",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Fecha que se envía evaluación técnica",
            ),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="fecha_recepcion_documento_regimen_interno",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de llegada de documento"
            ),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="fecha_respuesta_publicacionportal",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de respuesta"
            ),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="fecha_solicitud_regimen_interno",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Fecha de solicitud de régimen interno",
            ),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="fecha_subida_mercado_publico_adjudicacion",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="fecha_tentativa_cierre",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha tentativa de cierre"
            ),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="fecha_tope_firma_contrato",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha tope de firma de contrato"
            ),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="fecha_visita_terreno_publicacionportal",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de visita a terreno"
            ),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="monto_adjudicacion",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="nombre_integrante_dos_evaluacion",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="nombre_integrante_tres_evaluacion",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="nombre_integrante_uno_evaluacion",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="orden_compra_adjudicacion",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="rut_adjudicacion",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="licitacion",
            name="tipo_presupuesto",
            field=models.CharField(
                choices=[("le", "LE"), ("lp", "LP"), ("lr", "LR")],
                default="le",
                max_length=2,
                null=True,
                verbose_name="Tipo por presupuesto",
            ),
        ),
        migrations.CreateModel(
            name="DocumentoObservacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archivo", models.FileField(upload_to="documentos_licitacion/")),
                ("nombre", models.CharField(blank=True, max_length=255, null=True)),
                ("fecha_subida", models.DateTimeField(auto_now_add=True)),
                (
                    "bitacora",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archivos",
                        to="licitaciones.observacionbitacora",
                    ),
                ),
            ],
        ),
    ]
