# Generated by Django 3.2.15 on 2025-11-04 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('licitaciones', '0015_licitacion_empresa_adjudicacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observacionbitacora',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacoras_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('operador', 'Operador'), ('vizualizador', 'Vizualizador')], max_length=20),
        ),
    ]
