# Generated by Django 4.2.23 on 2025-09-06 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licitaciones", "0015_licitacion_empresa_adjudicacion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="licitacion",
            name="fecha_cierre_ofertas_mercado_publico",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Fecha de cierre de ofertas en mercado público",
            ),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="fecha_evaluacion_cotizacion",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Fecha de evaluacion de la cotizacion",
            ),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="fecha_publicación_mercado_publico",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Fecha de publicación en mercado público",
            ),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="fecha_solicitud_intencion_compra",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Fecha de la solicitud de intencion de compra",
            ),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="monto_estimado_cotizacion",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="nombre_integrante_dos_comision_base",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="nombre_integrante_tres_comision_base",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="nombre_integrante_uno_comision_base",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
