# Generated by Django 4.2.23 on 2025-09-17 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("licitaciones", "0015_licitacion_empresa_adjudicacion_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="licitacion",
            old_name="fecha_publicación_mercado_publico",
            new_name="fecha_publicacion_mercado_publico",
        ),
    ]
