# Generated by Django 4.2.23 on 2025-09-12 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "licitaciones",
            "0016_licitacion_fecha_cierre_ofertas_mercado_publico_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="licitacion",
            name="monto_estimado_cotizacion",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=15, null=True
            ),
        ),
    ]
