# Generated by Django 4.2.23 on 2025-08-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licitaciones", "0017_licitacion_fecha_vencimiento"),
    ]

    operations = [
        migrations.RenameField(
            model_name="licitacion",
            old_name="sigla",
            new_name="tipo_presupuesto",
        ),
    ]
