# Generated by Django 4.2.23 on 2025-08-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licitaciones", "0018_rename_sigla_licitacion_tipo_presupuesto_and_more"),
    ]

    operations = [
    ]
