# Generated by Django 4.2.23 on 2025-08-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licitaciones", "0019_licitacion_fecha_tentativa_termino_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="licitacion",
            name="tipo_presupuesto",
            field=models.CharField(
                choices=[("le", "LE"), ("lp", "LP"), ("lr", "LR")],
                default="le",
                max_length=2,
                verbose_name="Tipo de presupuesto",
            ),
        ),
    ]
