# Generated by Django 4.2.23 on 2025-08-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licitaciones", "0020_licitacion_fecha_tentativa_termino_and_more"),
    ]

    operations = [
    ]
