# Generated by Django 4.2.23 on 2025-08-22 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licitaciones", "0021_licitacion_fecha_vencimiento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="licitacion",
            name="tipo_presupuesto",
            field=models.CharField(
                choices=[("le", "LE"), ("lp", "LP"), ("lr", "LR")],
                default="LE",
                max_length=2,
                verbose_name="Tipo de presupuesto",
            ),
        ),
    ]
