# Generated by Django 4.2.23 on 2025-08-26 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("licitaciones", "0022_licitacion_fecha_vencimiento_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="licitacion",
            name="fecha_apertura_economica",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de apertura económica"
            ),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="fecha_apertura_tecnica",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de apertura técnica"
            ),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="fecha_cierre_oferta",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de cierre de oferta"
            ),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="fecha_cierre_preguntas",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de cierre de preguntas"
            ),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="fecha_respuesta",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de respuesta"
            ),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="fecha_tentativa_cierre",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha tentativa de cierre"
            ),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="fecha_visita_terreno",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de visita a terreno"
            ),
        ),
        migrations.AlterField(
            model_name="licitacion",
            name="tipo_presupuesto",
            field=models.CharField(
                choices=[("le", "LE"), ("lp", "LP"), ("lr", "LR")],
                default="le",
                max_length=2,
                null=True,
                verbose_name="Tipo por presupuesto",
            ),
        ),
    ]
