# Generated by Django 4.2.23 on 2025-08-26 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("licitaciones", "0022_licitacion_fecha_vencimiento_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentoObservacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archivo", models.FileField(upload_to="documentos_licitacion/")),
                ("nombre", models.CharField(blank=True, max_length=255, null=True)),
                ("fecha_subida", models.DateTimeField(auto_now_add=True)),
                (
                    "bitacora",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archivos",
                        to="licitaciones.observacionbitacora",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="licitacion",
            name="fecha_apertura_economica",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de apertura económica"
            ),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="fecha_apertura_tecnica",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de apertura técnica"
            ),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="fecha_cierre_oferta",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de cierre de oferta"
            ),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="fecha_cierre_preguntas",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de cierre de preguntas"
            ),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="fecha_respuesta",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de respuesta"
            ),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="fecha_tentativa_cierre",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha tentativa de cierre"
            ),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="fecha_visita_terreno",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de visita a terreno"
            ),
        ),
        migrations.AlterField(
            model_name="licitacion",
            name="tipo_presupuesto",
            field=models.CharField(
                choices=[("le", "LE"), ("lp", "LP"), ("lr", "LR")],
                default="le",
                max_length=2,
                null=True,
                verbose_name="Tipo por presupuesto",
            ),
        ),
    ]
