# Generated by Django 4.2.23 on 2025-08-27 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("licitaciones", "0023_licitacion_fecha_apertura_economica_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="licitacion",
            old_name="fecha_apertura_economica",
            new_name="fecha_apertura_economica_publicacionportal",
        ),
        migrations.RenameField(
            model_name="licitacion",
            old_name="fecha_apertura_tecnica",
            new_name="fecha_apertura_tecnica_publicacionportal",
        ),
        migrations.RenameField(
            model_name="licitacion",
            old_name="fecha_cierre_oferta",
            new_name="fecha_cierre_oferta_publicacionportal",
        ),
        migrations.RenameField(
            model_name="licitacion",
            old_name="fecha_cierre_preguntas",
            new_name="fecha_cierre_preguntas_publicacionportal",
        ),
        migrations.RenameField(
            model_name="licitacion",
            old_name="fecha_respuesta",
            new_name="fecha_respuesta_publicacionportal",
        ),
        migrations.RenameField(
            model_name="licitacion",
            old_name="fecha_visita_terreno",
            new_name="fecha_visita_terreno_publicacionportal",
        ),
        migrations.AddField(
            model_name="licitacion",
            name="empresa_adjudicacion",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="fecha_comision_evaluacion",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de comisión"
            ),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="fecha_decreto_adjudicacion",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="fecha_disponibilidad_presupuestaria",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Fecha que se pide disponibilidad presupuestaria",
            ),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="fecha_estimada_adjudicacion_publicacionportal",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha estimada de adjudicación"
            ),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="fecha_evaluacion_tecnica_evaluacion",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Fecha que se envía evaluación técnica",
            ),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="fecha_recepcion_documento_regimen_interno",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de llegada de documento"
            ),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="fecha_solicitud_regimen_interno",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Fecha de solicitud de régimen interno",
            ),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="fecha_subida_mercado_publico_adjudicacion",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="fecha_tope_firma_contrato",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha tope de firma de contrato"
            ),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="monto_adjudicacion",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="nombre_integrante_dos_evaluacion",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="nombre_integrante_tres_evaluacion",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="nombre_integrante_uno_evaluacion",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="orden_compra_adjudicacion",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="rut_adjudicacion",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
    ]
